In [38]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials

client_id = "70d5be9c5cd2437eacc8392f04833c36"
client_secret = "450e54f685384e5e812e3d2b4b3cfafb"

sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(
    client_id=client_id,
    client_secret=client_secret
))

In [39]:
results = sp.search(q="artist:Shakira track:Dai Dai", type="track", limit=1) # Search up the track 
print(type(results))
print(results)

<class 'dict'>
{'tracks': {'href': 'https://api.spotify.com/v1/search?offset=0&limit=1&query=artist%3AShakira%20track%3ADai%20Dai&type=track', 'limit': 1, 'next': None, 'offset': 0, 'previous': None, 'total': 1, 'items': [{'album': {'album_type': 'single', 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/0EmeFodog0BfCgMzAIvKQp'}, 'href': 'https://api.spotify.com/v1/artists/0EmeFodog0BfCgMzAIvKQp', 'id': '0EmeFodog0BfCgMzAIvKQp', 'name': 'Shakira', 'type': 'artist', 'uri': 'spotify:artist:0EmeFodog0BfCgMzAIvKQp'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/3wcj11K77LjEY1PkEazffa'}, 'href': 'https://api.spotify.com/v1/artists/3wcj11K77LjEY1PkEazffa', 'id': '3wcj11K77LjEY1PkEazffa', 'name': 'Burna Boy', 'type': 'artist', 'uri': 'spotify:artist:3wcj11K77LjEY1PkEazffa'}], 'external_urls': {'spotify': 'https://open.spotify.com/album/2eeufspLkAubwTJfOGSrI8'}, 'href': 'https://api.spotify.com/v1/albums/2eeufspLkAubwTJfOGSrI8', 'id': '2eeufspLkAubwTJfOGSrI8', 'images': [{'height': 640, 'width': 640, 'url': 'https://i.scdn.co/image/ab67616d0000b27303cadf1b3fe324c1dc710ed4'}, {'height': 300, 'width': 300, 'url': 'https://i.scdn.co/image/ab67616d00001e0203cadf1b3fe324c1dc710ed4'}, {'height': 64, 'width': 64, 'url': 'https://i.scdn.co/image/ab67616d0000485103cadf1b3fe324c1dc710ed4'}], 'is_playable': True, 'name': 'Dai Dai', 'release_date': '2026-05-14', 'release_date_precision': 'day', 'total_tracks': 1, 'type': 'album', 'uri': 'spotify:album:2eeufspLkAubwTJfOGSrI8'}, 'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/0EmeFodog0BfCgMzAIvKQp'}, 'href': 'https://api.spotify.com/v1/artists/0EmeFodog0BfCgMzAIvKQp', 'id': '0EmeFodog0BfCgMzAIvKQp', 'name': 'Shakira', 'type': 'artist', 'uri': 'spotify:artist:0EmeFodog0BfCgMzAIvKQp'}, {'external_urls': {'spotify': 'https://open.spotify.com/artist/3wcj11K77LjEY1PkEazffa'}, 'href': 'https://api.spotify.com/v1/artists/3wcj11K77LjEY1PkEazffa', 'id': '3wcj11K77LjEY1PkEazffa', 'name': 'Burna Boy', 'type': 'artist', 'uri': 'spotify:artist:3wcj11K77LjEY1PkEazffa'}], 'disc_number': 1, 'duration_ms': 223448, 'explicit': False, 'external_ids': {'isrc': 'USQX92602558'}, 'external_urls': {'spotify': 'https://open.spotify.com/track/0kosUz0jePvjiz4ctmR6wL'}, 'href': 'https://api.spotify.com/v1/tracks/0kosUz0jePvjiz4ctmR6wL', 'id': '0kosUz0jePvjiz4ctmR6wL', 'is_local': False, 'is_playable': True, 'name': 'Dai Dai', 'track_number': 1, 'type': 'track', 'uri': 'spotify:track:0kosUz0jePvjiz4ctmR6wL'}]}}

In [40]:
track_id = results['tracks']['items'][0]['id']

In [41]:
import pandas as pd

spotify_df = pd.read_csv('data/external/spotify-tracks-dataset.csv')

In [42]:
print(spotify_df.shape)
print(spotify_df.columns)
spotify_df.head()

(114000, 22)
Index(['Unnamed: 0.1', 'Unnamed: 0', 'track_id', 'artists', 'album_name',
       'track_name', 'popularity', 'duration_ms', 'explicit', 'danceability',
       'energy', 'key', 'loudness', 'mode', 'speechiness', 'acousticness',
       'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature',
       'track_genre'],
      dtype='str')

,Unnamed: 0.1,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.715,87.917,4,acoustic
1,1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.267,77.489,4,acoustic
2,2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.120,76.332,4,acoustic
3,3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.143,181.740,3,acoustic
4,4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.167,119.949,4,acoustic

In [43]:
spotify_df = spotify_df.drop(columns=['Unnamed: 0'], errors='ignore')

In [44]:
spotify_df

,Unnamed: 0.1,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,...,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,...,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,...,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,...,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,...,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

In [46]:
spotify_df['artists_clean'] = spotify_df['artists'].str.lower().str.strip()
spotify_df['track_name_clean'] = spotify_df['track_name'].str.lower().str.strip()

In [47]:
spotify_df

,Unnamed: 0.1,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,energy,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,artists_clean,track_name_clean
0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,0.4610,...,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic,gen hoshino,comedy
1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,0.1660,...,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic,ben woodward,ghost - acoustic
2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,0.3590,...,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic,ingrid michaelson;zayn,to begin again
3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,0.0596,...,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic,kina grannis,can't help falling in love
4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,0.4430,...,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic,chord overstreet,hold on
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,0.2350,...,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music,rainy lullaby,sleep my little boy
113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,0.1170,...,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music,rainy lullaby,water into light
113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,0.3290,...,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music,cesária evora,miss perfumado
113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,0.5060,...,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music,michael w. smith,friends
113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,0.4870,...,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music,cesária evora,barbincor

In [ ]:
merged = df.merge(
    spotify_df,
    left_on=['Artist_clean', 'Title_clean'],
    right_on=['artists_clean', 'track_name_clean'],
    how='left',
    indicator=True
)
match_rate = (merged['_merge'] == 'both').mean() * 100
print(f"Match rate: {match_rate:.1f}%")
print(merged.shape)

Match rate: 30.7%
(15094, 35)

In [57]:
merged

,Artist and Title,Days,T10,Pk,(x?),PkStreams,Total,Artist,Title,Artist_clean,...,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,artists_clean,track_name_clean,_merge
0,The Weeknd - Blinding Lights,2409,446.0,1,(x82),8453567,5399252326,The Weeknd,Blinding Lights,the weeknd,...,0.00146,0.000095,0.0897,0.334,171.005,4.0,pop,the weeknd,blinding lights,both
1,The Weeknd - Blinding Lights,2409,446.0,1,(x82),8453567,5399252326,The Weeknd,Blinding Lights,the weeknd,...,0.00147,0.000209,0.0938,0.344,171.014,4.0,pop,the weeknd,blinding lights,both
2,The Weeknd - Blinding Lights,2409,446.0,1,(x82),8453567,5399252326,The Weeknd,Blinding Lights,the weeknd,...,0.00147,0.000209,0.0938,0.344,171.014,4.0,pop,the weeknd,blinding lights,both
3,The Weeknd - Blinding Lights,2409,446.0,1,(x82),8453567,5399252326,The Weeknd,Blinding Lights,the weeknd,...,0.00147,0.000209,0.0938,0.344,171.014,4.0,pop,the weeknd,blinding lights,both
4,The Weeknd - Blinding Lights,2409,446.0,1,(x82),8453567,5399252326,The Weeknd,Blinding Lights,the weeknd,...,0.00147,0.000209,0.0938,0.344,171.014,4.0,pop,the weeknd,blinding lights,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15089,Wisin - Adrenalina,1,NaN,188,NaN,124862,124862,Wisin,Adrenalina,wisin,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
15090,Iggy Azalea - Work,1,NaN,196,NaN,120954,120954,Iggy Azalea,Work,iggy azalea,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
15091,Orup - Främling,1,NaN,199,NaN,120760,120760,Orup,Främling,orup,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
15092,Ed Sheeran - Nina,1,NaN,199,NaN,120515,120515,Ed Sheeran,Nina,ed sheeran,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
15093,Take That - These Days,1,NaN,198,NaN,115382,115382,Take That,These Days,take that,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [51]:
merged['_merge'].value_counts()

_merge
left_only     10462
both           4632
right_only        0
Name: count, dtype: int64

In [52]:
match_rate = (merged['_merge'] == 'both').mean() * 100
print(f"Match rate: {match_rate:.1f}%")

Match rate: 30.7%

In [53]:
print(df.shape)
df[['Artist', 'Title']].head(10)

(11795, 11)

              Artist                                          Title
0         The Weeknd                                Blinding Lights
1         Ed Sheeran                                   Shape of You
2       Harry Styles                                      As It Was
3  The Neighbourhood                                Sweater Weather
4      Lewis Capaldi                              Someone You Loved
5         The Weeknd                                        Starboy
6      Billie Eilish                             BIRDS OF A FEATHER
7          Lady Gaga                               Die With A Smile
8        Post Malone  Sunflower - Spider-Man: Into the Spider-Verse
9         Ed Sheeran                                        Perfect

In [54]:
df[['Artist', 'Artist_clean', 'Title', 'Title_clean']].sample(10)

,Artist,Artist_clean,Title,Title_clean
5973,Lil Uzi Vert,lil uzi vert,Bean (Kobe),bean (kobe)
8402,La Maquinaria Norteña,la maquinaria norteña,Eres Ese Algo,eres ese algo
10135,MACHETE,machete,MAMMASTOMALE,mammastomale
2342,Anuel AA,anuel aa,Hipócrita,hipócrita
10477,Ariana Grande,ariana grande,someone like u - interlude,someone like u - interlude
943,StaySolidRocky,staysolidrocky,Party Girl,party girl
11085,Tom Petty and the Heartbreakers,tom petty and the heartbreakers,Mary Jane's Last Dance,mary jane's last dance
7419,Daði Freyr,daði freyr,10 Years,10 years
7608,MØ,mø,Kamikaze,kamikaze
3222,Møme,møme,Aloha,aloha

In [55]:
merged[merged['Artist'].str.contains('Weeknd', na=False)][['Artist', 'Title', '_merge']]

           Artist                                   Title     _merge
0      The Weeknd                         Blinding Lights       both
1      The Weeknd                         Blinding Lights       both
2      The Weeknd                         Blinding Lights       both
3      The Weeknd                         Blinding Lights       both
4      The Weeknd                         Blinding Lights       both
...           ...                                     ...        ...
12062  The Weeknd                       Without a Warning  left_only
12451  The Weeknd  Nothing Is Lost (You Give Me Strength)  left_only
12867  The Weeknd          Nothing Compares - Bonus Track  left_only
12914  The Weeknd                Missed You - Bonus Track  left_only
13682  The Weeknd             Final Lullaby - Bonus Track  left_only

[111 rows x 3 columns]

In [58]:
final_df = merged[merged['_merge'] == 'both'].copy()
final_df = final_df.drop(columns=['_merge'])
print(final_df.shape)
final_df.to_csv('data/processed/final_matched_catalog.csv', index=False)

(4632, 34)