Reload the final df we created in enrichfeatures.ipynb

In [1]:
import pandas as pd

final_df = pd.read_csv('data/processed/final_matched_catalog.csv')
print(final_df.shape)
final_df.head()

(4632, 34)

,Artist and Title,Days,T10,Pk,(x?),PkStreams,Total,Artist,Title,Artist_clean,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,artists_clean,track_name_clean
0,The Weeknd - Blinding Lights,2416,446.0,1,(x82),8453567,5409337902,The Weeknd,Blinding Lights,the weeknd,...,0.0598,0.00146,0.000095,0.0897,0.334,171.005,4.0,pop,the weeknd,blinding lights
1,The Weeknd - Blinding Lights,2416,446.0,1,(x82),8453567,5409337902,The Weeknd,Blinding Lights,the weeknd,...,0.0645,0.00147,0.000209,0.0938,0.344,171.014,4.0,pop,the weeknd,blinding lights
2,The Weeknd - Blinding Lights,2416,446.0,1,(x82),8453567,5409337902,The Weeknd,Blinding Lights,the weeknd,...,0.0645,0.00147,0.000209,0.0938,0.344,171.014,4.0,pop,the weeknd,blinding lights
3,The Weeknd - Blinding Lights,2416,446.0,1,(x82),8453567,5409337902,The Weeknd,Blinding Lights,the weeknd,...,0.0645,0.00147,0.000209,0.0938,0.344,171.014,4.0,pop,the weeknd,blinding lights
4,The Weeknd - Blinding Lights,2416,446.0,1,(x82),8453567,5409337902,The Weeknd,Blinding Lights,the weeknd,...,0.0645,0.00147,0.000209,0.0938,0.344,171.014,4.0,pop,the weeknd,blinding lights

In [2]:
feature_cols = ['danceability', 'energy', 'loudness', 'speechiness',
                 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo']

print(final_df[feature_cols].dtypes)
final_df[feature_cols].describe()

danceability        float64
energy              float64
loudness            float64
speechiness         float64
acousticness        float64
instrumentalness    float64
liveness            float64
valence             float64
tempo               float64
dtype: object

,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo
count,4632.000000,4632.000000,4632.000000,4632.000000,4632.000000,4632.000000,4632.000000,4632.000000,4632.000000
mean,0.621309,0.631563,-6.704637,0.075498,0.266737,0.014383,0.181624,0.531937,118.284585
std,0.152954,0.200315,3.108473,0.071951,0.283340,0.079222,0.135823,0.232713,30.642383
min,0.128000,0.062300,-20.033000,0.022300,0.000008,0.000000,0.021900,0.037800,48.718000
25%,0.515000,0.522000,-7.870000,0.035400,0.036775,0.000000,0.092800,0.336000,94.033000
50%,0.623000,0.641000,-6.012000,0.048500,0.136000,0.000000,0.125000,0.538000,115.386500
75%,0.736000,0.787000,-4.457000,0.083000,0.456000,0.000120,0.252250,0.702250,137.963500
max,0.980000,0.995000,-0.173000,0.828000,0.994000,0.927000,0.923000,0.980000,216.334000

In [3]:
final_df[feature_cols].isna().sum()

danceability        0
energy              0
loudness            0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
dtype: int64

We should learn about how sklearn works conceptually tomorrow

In [4]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
# Standard Scaler is used to scale the features to have a mean of 0 and a standard deviation of 1. This is important because many machine learning algorithms perform better when the features are on a similar scale.

scaled_features = scaler.fit_transform(final_df[feature_cols])
# Data is analysed to learn that the mean and standard deviation of each feature, and then the data is transformed to have a mean of 0 and a standard deviation of 1.

In [5]:
# Turn it back into a dataframe with the same column names and index as the original dataframe
# Feature_cols come from the original dataframe, and the index is preserved to maintain the relationship between the scaled features and the original data.

scaled_df = pd.DataFrame(scaled_features, columns=feature_cols, index=final_df.index)
scaled_df.head()

,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo
0,-0.701651,0.491465,0.247942,-0.218206,-0.936349,-0.180364,-0.676868,-0.850654,1.720692
1,-0.714729,0.820982,0.846049,-0.152877,-0.936314,-0.178930,-0.646679,-0.807678,1.720986
2,-0.714729,0.820982,0.846049,-0.152877,-0.936314,-0.178930,-0.646679,-0.807678,1.720986
3,-0.714729,0.820982,0.846049,-0.152877,-0.936314,-0.178930,-0.646679,-0.807678,1.720986
4,-0.714729,0.820982,0.846049,-0.152877,-0.936314,-0.178930,-0.646679,-0.807678,1.720986

In [6]:
song_lookup = final_df[['Artist', 'Title']].reset_index(drop=True)
# reset_index(drop=True) is used to reset the index of the dataframe, which is useful when you want to create a new index for the dataframe. In this case, it is used to create a new index for the song_lookup dataframe, which contains the Artist and Title columns from the final_df dataframe.

In [7]:
final_df[['Artist', 'Title']].sample(5)

             Artist          Title
2991        Cardi B          Press
1850    Linkin Park          Faint
2110   KEVIN ROLDAN            PPP
1324  Calvin Harris         Summer
4327          Adele  Rumour Has It

In [8]:
sample_idx = final_df[final_df['Title'].str.contains('La Zona', case=False, na=False)].index
scaled_df.loc[sample_idx]

,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo
2313,0.919931,0.845945,0.979248,-0.480913,-0.235561,-0.18068,0.532926,1.195005,-0.792863
2314,0.919931,0.845945,0.979248,-0.480913,-0.235561,-0.18068,0.532926,1.195005,-0.792863

Noticing duplicate values, research on how this duplicate logic works

In [9]:
dupes = final_df[final_df.duplicated(subset=['Artist', 'Title'], keep=False)]
print(f"Number of duplicate rows: {len(dupes)}")
dupes[['Artist', 'Title']].sort_values('Title').head(20)

Number of duplicate rows: 4038

                Artist                             Title
3693  Blue Öyster Cult           (Don't Fear) The Reaper
3694  Blue Öyster Cult           (Don't Fear) The Reaper
3695  Blue Öyster Cult           (Don't Fear) The Reaper
3850      Otis Redding  (Sittin' On) the Dock of the Bay
3851      Otis Redding  (Sittin' On) the Dock of the Bay
1207            Maluma                             11 PM
1208            Maluma                             11 PM
1209            Maluma                             11 PM
2410             Lizzo           2 Be Loved (Am I Ready)
2411             Lizzo           2 Be Loved (Am I Ready)
2412             Lizzo           2 Be Loved (Am I Ready)
2413             Lizzo           2 Be Loved (Am I Ready)
2414             Lizzo           2 Be Loved (Am I Ready)
2415             Lizzo           2 Be Loved (Am I Ready)
2416             Lizzo           2 Be Loved (Am I Ready)
2417             Lizzo           2 Be Loved (Am I Ready)
2418             Lizzo           2 Be Loved (Am I Ready)
2419             Lizzo           2 Be Loved (Am I Ready)
2420             Lizzo           2 Be Loved (Am I Ready)
2421             Lizzo           2 Be Loved (Am I Ready)

In [10]:
final_df = final_df.drop_duplicates(subset=['Artist', 'Title'], keep='first')
final_df = final_df.reset_index(drop=True)
print(final_df.shape)

(1333, 34)

In [11]:
scaled_features = scaler.fit_transform(final_df[feature_cols])
scaled_df = pd.DataFrame(scaled_features, columns=feature_cols, index=final_df.index)

In [23]:
print(final_df.shape)
print(scaled_df.shape)

(1333, 34)
(1333, 9)

In [12]:
scaled_df

,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo
0,-0.727152,0.397511,0.165353,-0.256678,-0.864183,-0.188636,-0.666809,-0.708782,1.720570
1,-0.686531,0.402712,0.379752,-0.305038,0.422324,-0.178268,0.977621,0.766532,1.821993
2,1.378390,-0.008158,1.154968,-0.016053,1.325228,-0.189717,-0.641545,1.976468,-0.880988
3,-0.063670,0.797978,1.289147,-0.565715,-0.682695,0.010918,-0.582841,-0.420916,0.092533
4,-0.815165,-1.292774,0.257084,-0.585767,1.967461,-0.189717,-0.553118,-0.205016,-0.398527
...,...,...,...,...,...,...,...,...,...
1328,-0.260006,0.485926,0.273632,0.021692,0.237209,-0.115357,3.563531,0.766532,1.368971
1329,-2.128590,-1.162752,-1.776824,-0.220112,0.218320,-0.178450,-0.599189,-0.839221,0.826627
1330,-0.266777,-1.594424,-3.012854,-0.602280,0.327878,-0.112864,-0.508534,-1.852599,-0.812332
1331,1.385160,-0.850699,-1.468896,-0.164674,-0.835093,-0.189667,-1.024973,0.609105,-1.638660
1332,0.234221,1.162039,1.137701,-0.558638,0.433657,-0.189717,1.259991,1.810046,-0.567496

In [13]:
final_df.duplicated(subset=['Artist', 'Title']).sum()

np.int64(0)

In [14]:
sample_idx = final_df[final_df['Title'].str.contains('La Zona', case=False, na=False)].index
scaled_df.loc[sample_idx]

,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo
555,0.951865,0.766773,0.983017,-0.479609,-0.11413,-0.188919,0.554067,1.432222,-0.949817

User profile representation section

In [15]:
final_df[['Artist', 'Title']].sample(10)

              Artist                                        Title
288  Imagine Dragons                                  Radioactive
931              BTS                                   Magic Shop
84       Frank Ocean                                 Pink + White
577        BLACKPINK                                    Typa Girl
646       Bea Miller                               feel something
200              Sia                                   Chandelier
733        BLACKPINK                               You Never Know
75     Michael Bublé  It's Beginning to Look a Lot like Christmas
290   Ellie Goulding                                   On My Mind
968   Arctic Monkeys                                Golden Trunks

In [16]:
liked_titles = ['Sauce!', 'God\'s Plan', 'Be My Mistake', 'Lover', 'Electric Love', 'Mama, I\'m Coming Home', 'Fortunate Son', 'The Kind Of Love We Make', 'MONEY', 'Love Me Do - Remastered 2009']

In [17]:
import pandas as pd

# Sample Series
ages = pd.Series([25, 30, 35, 40])

# Check if values exist in the list
print(ages.isin([30, 40]))

print(ages.isin([30, 40]).index)

0    False
1     True
2    False
3     True
dtype: bool
RangeIndex(start=0, stop=4, step=1)

In [18]:
final_df[final_df['Title'].isin(liked_titles)]

,Artist and Title,Days,T10,Pk,(x?),PkStreams,Total,Artist,Title,Artist_clean,...,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre,artists_clean,track_name_clean
54,Drake - God's Plan,717,146.0,1,(x74),8553009,1419636888,Drake,God's Plan,drake,...,0.1090,0.03320,0.000083,0.5520,0.3570,77.169,4.0,hip-hop,drake,god's plan
121,Taylor Swift - Lover,518,9.0,2,(x2),5550879,806188610,Taylor Swift,Lover,taylor swift,...,0.0915,0.49200,0.000016,0.1180,0.4530,68.505,4.0,pop,taylor swift,lover
199,LISA - MONEY,266,31.0,5,NaN,4359380,456750403,LISA,MONEY,lisa,...,0.2340,0.16300,0.000041,0.1350,0.4000,140.037,4.0,k-pop,lisa,money
348,BØRNS - Electric Love,245,NaN,60,NaN,1264288,187558590,BØRNS,Electric Love,børns,...,0.0533,0.00543,0.001370,0.2600,0.5180,120.041,4.0,rock,børns,electric love
514,Creedence Clearwater Revival - Fortunate Son,62,NaN,71,NaN,1681564,79501028,Creedence Clearwater Revival,Fortunate Son,creedence clearwater revival,...,0.0373,0.20100,0.008060,0.1520,0.6650,132.768,4.0,country,creedence clearwater revival,fortunate son
776,"Ozzy Osbourne - Mama, I'm Coming Home",7,NaN,17,NaN,3250743,13483023,Ozzy Osbourne,"Mama, I'm Coming Home",ozzy osbourne,...,0.0302,0.01050,0.000000,0.0892,0.2420,139.352,4.0,hard-rock,ozzy osbourne,"mama, i'm coming home"
791,XXXTENTACION - Sauce!,14,NaN,64,NaN,1259195,12493544,XXXTENTACION,Sauce!,xxxtentacion,...,0.0347,0.58200,0.000000,0.1900,0.4050,135.034,4.0,emo,xxxtentacion,sauce!
1128,The Beatles - Love Me Do - Remastered 2009,4,NaN,122,NaN,313318,1110377,The Beatles,Love Me Do - Remastered 2009,the beatles,...,0.0806,0.38600,0.000062,0.2270,0.7440,147.997,4.0,british,the beatles,love me do - remastered 2009
1254,The 1975 - Be My Mistake,1,NaN,200,NaN,703181,703181,The 1975,Be My Mistake,the 1975,...,0.0344,0.83500,0.000137,0.0906,0.0949,109.923,3.0,rock,the 1975,be my mistake

In [19]:
liked_idx = final_df[final_df['Title'].isin(liked_titles)].index
print(liked_idx)

Index([54, 121, 199, 348, 514, 776, 791, 1128, 1254], dtype='int64')

In [20]:
liked_vectors = scaled_df.loc[liked_idx]
liked_vectors

,danceability,energy,loudness,speechiness,acousticness,instrumentalness,liveness,valence,tempo
54,0.897703,-1.063935,-1.013479,0.323652,-0.744274,-0.188777,2.768438,-0.605330,-1.533146
121,-1.776538,-0.575053,-0.427480,0.117234,0.989000,-0.189539,-0.456518,-0.173531,-1.833565
199,1.385160,-0.523044,-1.340833,1.798066,-0.253910,-0.189250,-0.330195,-0.411920,0.646771
348,-0.070440,0.745969,-0.443668,-0.333347,-0.849185,-0.174188,0.598652,0.118833,-0.046581
514,0.125897,0.049052,-0.403738,-0.522072,-0.110352,-0.098354,-0.203872,0.780025,0.394722
776,-2.297846,0.012646,-0.058758,-0.605819,-0.830031,-0.189717,-0.670525,-1.122589,0.623019
791,0.396706,-1.771254,-2.618231,-0.552740,1.329006,-0.189717,0.078498,-0.389430,0.473294
1128,-0.686531,0.912397,0.059593,-0.011335,0.588549,-0.189014,0.353436,1.135360,0.922780
1254,-0.334479,-2.592992,-2.881912,-0.556279,2.284800,-0.188164,-0.660121,-1.784231,-0.397417

In [21]:
user_profile = liked_vectors.mean(axis=0)
print(user_profile)

danceability       -0.262263
energy             -0.534024
loudness           -1.014279
speechiness        -0.038071
acousticness        0.267067
instrumentalness   -0.177413
liveness            0.164199
valence            -0.272535
tempo              -0.083347
dtype: float64

In [22]:
print(liked_vectors)
print(user_profile)

      danceability    energy  loudness  speechiness  acousticness  \
54        0.897703 -1.063935 -1.013479     0.323652     -0.744274
121      -1.776538 -0.575053 -0.427480     0.117234      0.989000
199       1.385160 -0.523044 -1.340833     1.798066     -0.253910
348      -0.070440  0.745969 -0.443668    -0.333347     -0.849185
514       0.125897  0.049052 -0.403738    -0.522072     -0.110352
776      -2.297846  0.012646 -0.058758    -0.605819     -0.830031
791       0.396706 -1.771254 -2.618231    -0.552740      1.329006
1128     -0.686531  0.912397  0.059593    -0.011335      0.588549
1254     -0.334479 -2.592992 -2.881912    -0.556279      2.284800

      instrumentalness  liveness   valence     tempo
54           -0.188777  2.768438 -0.605330 -1.533146
121          -0.189539 -0.456518 -0.173531 -1.833565
199          -0.189250 -0.330195 -0.411920  0.646771
348          -0.174188  0.598652  0.118833 -0.046581
514          -0.098354 -0.203872  0.780025  0.394722
776          -0.189717 -0.670525 -1.122589  0.623019
791          -0.189717  0.078498 -0.389430  0.473294
1128         -0.189014  0.353436  1.135360  0.922780
1254         -0.188164 -0.660121 -1.784231 -0.397417
danceability       -0.262263
energy             -0.534024
loudness           -1.014279
speechiness        -0.038071
acousticness        0.267067
instrumentalness   -0.177413
liveness            0.164199
valence            -0.272535
tempo              -0.083347
dtype: float64